name: Generate Sitemap

on:
  push:
    branches:
      - main  # Change if your main branch is named differently

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://physiolinkexpo.com.my/

      - name: Upload sitemap to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Add/update sitemap.xml" || echo "No changes to commit"
          git push
